["protostar.config"]
protostar_version = "0.2.3"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
cairo-path = ["./lib/imx_starknet/lib/cairo_contracts/src/"]

["protostar.contracts"]
main = [
    "./src/Pixelium.cairo",
]
